--Описание структуры: у каждого человека есть машина. Причем несколько человек могут
-- пользоваться одной машиной. У каждого человека есть имя, возраст и признак того,
-- что у него есть права (или их нет). У каждой машины есть марка, модель и стоимость.
-- Также не забудьте добавить таблицам первичные ключи и связать их.

create table car(
                    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                    brand varchar,
                    model varchar,
                    price int
);

create table person(
                       id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                       name varchar,
                       age int,
                       has_driver_licence boolean,
                       car int REFERENCES car(id) NOT NULL
);